### ISSUE TITLE
Create Transformer Embeddings error

### ISSUE THREAD

**Issue by julfr** [Dennis1989/RP-Mod-RP-Crowd#2]
Hi, I try to reproduce your results with language models and try to execute `create_transformer_embeddings.ipynb` script.
I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '../../Dataset/Embeddings/derstandard-folds-bert-base-german-cased.npz'
`
Could it be, that some scripts are missing in preprocessing stage?

**Comment by mvseiler** [comment]
Hi, it would be great if you could also provide the exact command. I guess it's this command: `np.savez_compressed`? Then please ensure that the following folder exists:`../../Dataset/Embeddings/`
